version: '3.1'
services:
  hangar:
    build: '.'
    restart: unless-stopped
    container_name: hangar-bot
    env_file:
      .env
    volumes:
      - data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.hangar-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.hangar-secure.entrypoints=websecure"
      - "traefik.http.routers.hangar-secure.tls=true"
      - "traefik.http.routers.hangar-secure.tls.certresolver=letsencrypt"
    networks:
      - web
volumes:
  data:
networks:
  web:
    external: true
