version: '3.1'
services:
  hangar:
    build: '.'
    restart: unless-stopped
    container_name: hangar-bot
    env_file:
      .env
    volumes:
      - data:data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
      - "traefik.http.routers.wordpress.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.routers.wordpress-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.wordpress-secure.entrypoints=websecure"
      - "traefik.http.routers.wordpress-secure.tls=true"
      - "traefik.http.routers.wordpress-secure.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.redirecthttps.redirectscheme.scheme=https"
      - "traefik.http.routers.wordpress.middlewares=redirecthttps"
    networks:
      - web
volumes:
  data:
networks:
  web:
    external: true
